### ISSUE TITLE
This should be a package instead of a raw latex file

### ISSUE THREAD

**Issue by jeffgerickson** [lukeolson/illinois-letterhead#4]
This really should be formatted as a latex package, so the user can write \usepackage{illinois-letterhead} in the preamble instead of \input{illinois}.

This could be as simple as renaming the file "illinois-letterhead.sty".

**Comment by lukeolson** [comment]
Good point.  Initially I went with `\input{}` since it could handle relative paths.  However one could use the `.sty` with symlinks (as in the example) or `kpsewhich` or `TEXINPUTS`.  Check out the stylizing here: [illinois-letterhead/stylize](https://github.com/lukeolson/illinois-letterhead/tree/stylize)

This allows for `\usepackage[layout]{illinois-letterhead}`.  If this looks good, then I'll merge and add a possible workflow in the instructions.

Note -- I do not foresee packaging this package due to the needed logo files.

Thanks for your \input!

**Comment by lukeolson** [comment]
merge with master 63db0612091fe746c166bd5984ba1f280418110a
